#pragma once

#define PINSIBLEATAS 33
#define PINSIBLEBAWAH 14
#define PINBUKASTOPKRAN 32
#define PINTUTUPSTOPKRAN 21

#define PINSTOPKRANSELATAN 22
#define PINSTOPKRANUTARA 23
#define STATE_DELAY 5000

enum SystemMode {
  MODE_DAY,
  MODE_NIGHT,
  MODE_STARTING
};

enum PLC_State {
  SIBLE_OFF_ALL,
  SIBLE_BAWAH_ON,
  SIBLE_DUA_ON,
  SIBLE_DUA_ON1,
  PLC_ERROR
};

enum ValveState {
  VALVE_IDLE,
  VALVE_OPENING,
  VALVE_CLOSING,
  VALVE_SETTLING
};